spring:
  application:
    name: FINDY_BE

  profiles:
    active: ${profile}
    include:
      - oauth

jwt:
  secretKey: ${JWT_SECRET}

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: "Authorization"

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: "Authorization-refresh"

springdoc:
  api-docs:
    path: /findy/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /findy/api-docs.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none