spring:
  application:
    name: FINDY_BE

  docker:
    compose:
      file: ./docker/compose-local.yaml

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3320/findy-db
    username: root
    password: findydb!

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace