spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc.lob.non_contextual_creation: true
    defer-datasource-initialization: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace