spring:
  application:
    name: FINDY_BE

  profiles:
    active: ${profile}
    include:
      - oauth

springdoc:
  api-docs:
    path: /findy/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /findy/api-docs.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

server:
  url: ${SERVER_URL:http://localhost:8080}