services:
  findy-db:
    image: postgres:latest
    platform: linux/x86_64
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: findy-db
      POSTGRES_USER: findy
      POSTGRES_PASSWORD: findydb!
      TZ: Asia/Seoul
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
      - ./db/postgresql/config:/etc/postgresql/conf.d
networks:
  findy-db-local: