package org.findy.findy_be.place.domain;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Schema(description = "즐겨찾기 중분류", enumAsRef = true)
@Getter
@RequiredArgsConstructor
public enum MiddleCategory {

	// 음식점 중분류
	KOREAN(MajorCategory.RESTAURANT, "한식"),
	JAPANESE(MajorCategory.RESTAURANT, "일식"),
	WESTERN(MajorCategory.RESTAURANT, "양식"),
	CHINESE(MajorCategory.RESTAURANT, "중식"),
	KOREAN_STREET_FOOD(MajorCategory.RESTAURANT, "분식"),
	OTHER_FOOD(MajorCategory.RESTAURANT, "기타 음식"),

	// 카페/디저트 중분류
	ICE_CREAM(MajorCategory.CAFE_AND_DESSERT, "아이스크림"),
	WAFFLE(MajorCategory.CAFE_AND_DESSERT, "와플"),
	BAKERY(MajorCategory.CAFE_AND_DESSERT, "베이커리"),
	CHOCOLATE(MajorCategory.CAFE_AND_DESSERT, "초콜릿전문점"),
	TAKEOUT_COFFEE(MajorCategory.CAFE_AND_DESSERT, "테이크아웃커피"),
	TEA(MajorCategory.CAFE_AND_DESSERT, "홍차전문점"),
	CAKE(MajorCategory.CAFE_AND_DESSERT, "케이크전문"),
	BOOK_CAFE(MajorCategory.CAFE_AND_DESSERT, "북카페"),
	FLOWER_CAFE(MajorCategory.CAFE_AND_DESSERT, "플라워카페"),
	BRUNCH_CAFE(MajorCategory.CAFE_AND_DESSERT, "브런치카페"),
	FRUIT_JUICE(MajorCategory.CAFE_AND_DESSERT, "과일/주스전문점"),

	// 술집 중분류
	WINE(MajorCategory.BAR, "와인"),
	BAR(MajorCategory.BAR, "바(BAR)"),
	ODENG_SKEWER(MajorCategory.BAR, "오뎅/꼬치"),
	POJANGMACHA(MajorCategory.BAR, "포장마차"),
	DINING_BAR(MajorCategory.BAR, "요리주점"),
	BEER_HOF(MajorCategory.BAR, "맥주/호프"),
	IZAKAYA(MajorCategory.BAR, "이자카야"),
	TRADITIONAL_BAR(MajorCategory.BAR, "전통/민속주점"),

	// 쇼핑, 유통 중분류
	TRADITIONAL_FOOD(MajorCategory.SHOPPING_AND_DISTRIBUTION, "전통식품"),
	DELICATESSEN(MajorCategory.SHOPPING_AND_DISTRIBUTION, "반찬가게"),
	EYEWEAR(MajorCategory.SHOPPING_AND_DISTRIBUTION, "안경원"),
	JEWELRY(MajorCategory.SHOPPING_AND_DISTRIBUTION, "귀금속/시계"),
	FUNCTIONAL_WEAR(MajorCategory.SHOPPING_AND_DISTRIBUTION, "기능성의류"),
	DEPARTMENT_STORE(MajorCategory.SHOPPING_AND_DISTRIBUTION, "백화점"),
	BOOKSTORE(MajorCategory.SHOPPING_AND_DISTRIBUTION, "서점"),
	SUPERMARKET(MajorCategory.SHOPPING_AND_DISTRIBUTION, "슈퍼/마트"),
	SHOES(MajorCategory.SHOPPING_AND_DISTRIBUTION, "신발"),
	CASUAL_WEAR(MajorCategory.SHOPPING_AND_DISTRIBUTION, "캐주얼웨어"),
	FURNITURE(MajorCategory.SHOPPING_AND_DISTRIBUTION, "가구/인테리어"),
	BICYCLE(MajorCategory.SHOPPING_AND_DISTRIBUTION, "자전거"),
	BUTCHER(MajorCategory.SHOPPING_AND_DISTRIBUTION, "정육점"),
	GENERAL_APPLIANCES(MajorCategory.SHOPPING_AND_DISTRIBUTION, "종합가전"),
	USED_PHONE(MajorCategory.SHOPPING_AND_DISTRIBUTION, "중고폰"),
	BEDDING(MajorCategory.SHOPPING_AND_DISTRIBUTION, "침구/커튼"),
	CERAMICS(MajorCategory.SHOPPING_AND_DISTRIBUTION, "도자기"),
	SEAFOOD(MajorCategory.SHOPPING_AND_DISTRIBUTION, "수산물"),
	FASHION(MajorCategory.SHOPPING_AND_DISTRIBUTION, "패션"),
	PERFUME(MajorCategory.SHOPPING_AND_DISTRIBUTION, "향수"),
	COSMETICS(MajorCategory.SHOPPING_AND_DISTRIBUTION, "화장품/향수"),

	// 여행, 명소 중분류
	THEME_PARK(MajorCategory.TRAVEL_AND_ATTRACTION, "테마파크"),
	TOUR_EXPERIENCE(MajorCategory.TRAVEL_AND_ATTRACTION, "관람/체험"),
	CITY_THEME_PARK(MajorCategory.TRAVEL_AND_ATTRACTION, "도시/테마공원"),
	ANIMAL_PARK(MajorCategory.TRAVEL_AND_ATTRACTION, "동물원"),
	MUSEUM(MajorCategory.TRAVEL_AND_ATTRACTION, "박물관"),
	BOTANICAL_GARDEN(MajorCategory.TRAVEL_AND_ATTRACTION, "식물원/수목원"),
	SPA(MajorCategory.TRAVEL_AND_ATTRACTION, "온천/스파"),
	ECO_PARK(MajorCategory.TRAVEL_AND_ATTRACTION, "자연/생태공원"),
	NATURE_PARK(MajorCategory.TRAVEL_AND_ATTRACTION, "자연공원"),
	FARM_STAY(MajorCategory.TRAVEL_AND_ATTRACTION, "관광농원/팜스테이"),
	RAIL_BIKE(MajorCategory.TRAVEL_AND_ATTRACTION, "레일바이크"),
	RECREATION_AREA(MajorCategory.TRAVEL_AND_ATTRACTION, "유원지"),
	OBSERVATORY(MajorCategory.TRAVEL_AND_ATTRACTION, "천문대"),
	VILLAGE_EXPERIENCE(MajorCategory.TRAVEL_AND_ATTRACTION, "체험마을"),
	TRAVEL_EXPERIENCE(MajorCategory.TRAVEL_AND_ATTRACTION, "체험여행"),
	CABLE_CAR(MajorCategory.TRAVEL_AND_ATTRACTION, "케이블카"),
	MONORAIL(MajorCategory.TRAVEL_AND_ATTRACTION, "모노레일"),
	ZIPLINE(MajorCategory.TRAVEL_AND_ATTRACTION, "짚라인"),
	BUNGEE_JUMPING(MajorCategory.TRAVEL_AND_ATTRACTION, "번지점프"),
	WATER_SPORTS(MajorCategory.TRAVEL_AND_ATTRACTION, "수상/해양레저"),
	SPORTS_FACILITY(MajorCategory.TRAVEL_AND_ATTRACTION, "스포츠시설"),
	SCREEN_GOLF(MajorCategory.TRAVEL_AND_ATTRACTION, "스크린골프장"),
	YOGA(MajorCategory.TRAVEL_AND_ATTRACTION, "요가원"),
	PILATES(MajorCategory.TRAVEL_AND_ATTRACTION, "필라테스"),
	GYM(MajorCategory.TRAVEL_AND_ATTRACTION, "헬스장"),
	HOTEL(MajorCategory.TRAVEL_AND_ATTRACTION, "호텔"),
	MOTEL(MajorCategory.TRAVEL_AND_ATTRACTION, "모텔"),
	PENSION(MajorCategory.TRAVEL_AND_ATTRACTION, "펜션"),
	GUESTHOUSE(MajorCategory.TRAVEL_AND_ATTRACTION, "게스트하우스"),
	CONDO_RESORT(MajorCategory.TRAVEL_AND_ATTRACTION, "콘도/리조트"),
	RESIDENCE(MajorCategory.TRAVEL_AND_ATTRACTION, "레지던스"),
	TRADITIONAL_ACCOMMODATION(MajorCategory.TRAVEL_AND_ATTRACTION, "전통숙소"),
	CAMPING(MajorCategory.TRAVEL_AND_ATTRACTION, "캠핑/야영장"),
	HOMESTAY(MajorCategory.TRAVEL_AND_ATTRACTION, "민박"),

	// 공공, 사회 중분류
	LIBRARY(MajorCategory.PUBLIC_AND_SOCIAL, "도서관"),
	TRAINING_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "수련원/연수원"),
	DAYCARE(MajorCategory.PUBLIC_AND_SOCIAL, "어린이집"),
	PUBLIC_KINDERGARTEN(MajorCategory.PUBLIC_AND_SOCIAL, "병설유치원"),
	KINDERGARTEN(MajorCategory.PUBLIC_AND_SOCIAL, "유치원"),
	DISTRICT_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "구청"),
	NATIONAL_VETERANS_AGENCY(MajorCategory.PUBLIC_AND_SOCIAL, "국가보훈부"),
	TAX_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "국세청"),
	WEATHER_AGENCY(MajorCategory.PUBLIC_AND_SOCIAL, "기상청"),
	SUPREME_COURT(MajorCategory.PUBLIC_AND_SOCIAL, "대법원"),
	EMBASSY_CONSULATE(MajorCategory.PUBLIC_AND_SOCIAL, "대사관/영사관"),
	REGISTRY_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "등기소"),
	CIVIL_SERVICE_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "민원/상담"),
	MUNICIPAL_TAX_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "세무서"),
	CITY_HALL(MajorCategory.PUBLIC_AND_SOCIAL, "시청"),
	POST_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "우체국"),
	IMMIGRATION_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "출입국외국인정책본부"),
	REGIONAL_LABOR_OFFICE(MajorCategory.PUBLIC_AND_SOCIAL, "지방노동청"),
	DISTRICT_COURT(MajorCategory.PUBLIC_AND_SOCIAL, "지방법원"),
	REGIONAL_ENVIRONMENT_AGENCY(MajorCategory.PUBLIC_AND_SOCIAL, "지방환경청"),
	YOUTH_FACILITY(MajorCategory.PUBLIC_AND_SOCIAL, "청소년시설"),
	CENTRAL_ADMINISTRATION(MajorCategory.PUBLIC_AND_SOCIAL, "중앙행정기관"),
	METROPOLITAN_CITY_HALL(MajorCategory.PUBLIC_AND_SOCIAL, "특별/광역시청"),
	COMMUNITY_WELFARE_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "행정복지센터"),
	FIRE_SAFETY_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "119안전센터"),
	FIRE_HEADQUARTERS(MajorCategory.PUBLIC_AND_SOCIAL, "소방본부"),
	FIRE_STATION(MajorCategory.PUBLIC_AND_SOCIAL, "소방서"),
	POLICE_BOX(MajorCategory.PUBLIC_AND_SOCIAL, "파출소"),
	WOMEN_CHILD_WELFARE(MajorCategory.PUBLIC_AND_SOCIAL, "여성/모자/부자복지시설"),
	FOREIGN_WELFARE(MajorCategory.PUBLIC_AND_SOCIAL, "외국인복지시설"),
	HOME_ELDERLY_CARE(MajorCategory.PUBLIC_AND_SOCIAL, "재가노인요양센터"),
	GENERAL_SOCIAL_WELFARE_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "종합사회복지관"),
	LOCAL_WELFARE_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "지역복지센터"),
	YOUTH_ACTIVITY_CENTER(MajorCategory.PUBLIC_AND_SOCIAL, "청소년활동시설"),

	// 병원, 의원 중분류
	GENERAL_HOSPITAL(MajorCategory.HOSPITAL_AND_CLINIC, "종합병원"),
	REHABILITATION_HOSPITAL(MajorCategory.HOSPITAL_AND_CLINIC, "요양병원"),
	HEALTH_CENTER(MajorCategory.HOSPITAL_AND_CLINIC, "보건소"),
	HEALTH_SUB_CENTER(MajorCategory.HOSPITAL_AND_CLINIC, "보건지소"),
	WOMEN_COUNSELING(MajorCategory.HOSPITAL_AND_CLINIC, "여성상담"),
	WOMEN_HOSPITAL(MajorCategory.HOSPITAL_AND_CLINIC, "여성전문병원"),
	ANIMAL_HOSPITAL(MajorCategory.HOSPITAL_AND_CLINIC, "동물병원"),
	FAMILY_MEDICINE(MajorCategory.HOSPITAL_AND_CLINIC, "가정의학과"),
	INTERNAL_MEDICINE(MajorCategory.HOSPITAL_AND_CLINIC, "내과"),
	ANESTHESIOLOGY(MajorCategory.HOSPITAL_AND_CLINIC, "마취통증의학과"),
	UROLOGY(MajorCategory.HOSPITAL_AND_CLINIC, "비뇨의학과"),
	OBSTETRICS(MajorCategory.HOSPITAL_AND_CLINIC, "산부인과"),
	PLASTIC_SURGERY(MajorCategory.HOSPITAL_AND_CLINIC, "성형외과"),
	NEUROSURGERY(MajorCategory.HOSPITAL_AND_CLINIC, "신경외과"),
	OPHTHALMOLOGY(MajorCategory.HOSPITAL_AND_CLINIC, "안과"),
	OTOLARYNGOLOGY(MajorCategory.HOSPITAL_AND_CLINIC, "이비인후과"),
	ORTHOPEDICS(MajorCategory.HOSPITAL_AND_CLINIC, "정형외과"),
	DENTAL_CLINIC(MajorCategory.HOSPITAL_AND_CLINIC, "치과"),
	DERMATOLOGY(MajorCategory.HOSPITAL_AND_CLINIC, "피부과"),
	ORIENTAL_MEDICINE(MajorCategory.HOSPITAL_AND_CLINIC, "한의원"),
	CHEST_SURGERY(MajorCategory.HOSPITAL_AND_CLINIC, "흉부외과"),

	// 기타 중분류
	CONVENIENCE_STORE(MajorCategory.OTHER, "편의점"),
	WORKSHOP(MajorCategory.OTHER, "공방"),
	FLOWER_SHOP(MajorCategory.OTHER, "꽃집/꽃배달"),
	MENS_HAIRCUT(MajorCategory.OTHER, "남성전문미용실"),
	BATHHOUSE_SAUNA(MajorCategory.OTHER, "목욕탕/사우나"),
	HAIR_SALON(MajorCategory.OTHER, "미용실"),
	NAIL_SALON(MajorCategory.OTHER, "네일아트/네일샵"),
	SCALP_CARE(MajorCategory.OTHER, "두피/탈모관리"),
	MASSAGE(MajorCategory.OTHER, "마사지/지압"),
	FOOT_CARE(MajorCategory.OTHER, "발관리"),
	EYELASH_EXTENSION(MajorCategory.OTHER, "속눈썹증모/연장"),
	WAXING(MajorCategory.OTHER, "왁싱/제모"),
	SKIN_AND_BODY_CARE(MajorCategory.OTHER, "피부/체형관리"),
	BARBERSHOP(MajorCategory.OTHER, "이용원"),

	RELIGION_BUDDHISM(MajorCategory.OTHER, "불교"),
	RELIGION_CHRISTIANITY(MajorCategory.OTHER, "개신교"),
	PAYPHONE(MajorCategory.OTHER, "공중전화"),
	DIRECTIONAL_INFO(MajorCategory.OTHER, "방면정보"),
	HEALTH_MANAGEMENT(MajorCategory.OTHER, "건강관리"),
	ENTREPRENEUR_SUPPORT(MajorCategory.OTHER, "창업/소호"),
	HOUSING(MajorCategory.OTHER, "주택"),
	HIKING_TRAIL(MajorCategory.OTHER, "등산코스"),
	PUBLIC_RESTROOM(MajorCategory.OTHER, "화장실"),
	CORPORATE(MajorCategory.OTHER, "기업"),
	BUSINESS_CONSULTING(MajorCategory.OTHER, "경영컨설팅"),
	VENUE_RENTAL(MajorCategory.OTHER, "장소대여"),
	ATM(MajorCategory.OTHER, "현금인출기");

	private final MajorCategory majorCategory;
	private final String label;
}